import React from "react";
import {
  Activity,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Award,
  Baby,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Building,
  Bus,
  CalendarClock,
  Car,
  CircleDollarSign,
  Coffee,
  Coins,
  CreditCard,
  Film,
  Gift,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  type LucideIcon,
  MoreHorizontal,
  Music,
  PiggyBank,
  Plane,
  Receipt,
  Scale,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Tag,
  Target,
  TrendingUp,
  Tv,
  User,
  Utensils,
  Wallet as WalletIcon,
  Zap,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  landmark: Landmark,
  smartphone: Smartphone,
  banknote: Banknote,
  "credit-card": CreditCard,
  wallet: WalletIcon,
  coins: Coins,
  building: Building,
  "shield-check": ShieldCheck,
  bike: Bike,
  heart: Heart,
  car: Car,
  plane: Plane,
  home: Home,
  laptop: Laptop,
  target: Target,
  sparkles: Sparkles,
  "piggy-bank": PiggyBank,
  "graduation-cap": GraduationCap,
  utensils: Utensils,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  receipt: Receipt,
  film: Film,
  "heart-pulse": HeartPulse,
  "more-horizontal": MoreHorizontal,
  briefcase: Briefcase,
  gift: Gift,
  "trending-up": TrendingUp,
  tag: Tag,
  "arrow-down-left": ArrowDownLeft,
  "arrow-up-right": ArrowUpRight,
  "arrow-left-right": ArrowLeftRight,
  "hand-coins": HandCoins,
  scale: Scale,
  "calendar-clock": CalendarClock,
  user: User,
  baby: Baby,
  activity: Activity,
  coffee: Coffee,
  bus: Bus,
  tv: Tv,
  shirt: Shirt,
  music: Music,
  "book-open": BookOpen,
  award: Award,
  zap: Zap,
  "circle-dollar-sign": CircleDollarSign,
};

interface DynamicIconProps {
  name: string;
  className?: string;
  strokeWidth?: number;
}

export function DynamicIcon({
  name,
  className = "w-4 h-4",
  strokeWidth = 1.75,
}: DynamicIconProps) {
  const IconComponent = ICON_MAP[name] ?? Tag;
  return <IconComponent className={className} strokeWidth={strokeWidth} />;
}
